### ISSUE TITLE
Search key by description and name

### ISSUE THREAD

**Issue by mansivirani** [NYU-DevOps-Charlie-CSCI-GA-3033-013/products#18]
Keyword searching by the attributes description/name/category from the schema.

**Comment by ephraimrosenfeld** [comment]
Example:
GET /products?search=abc

Should return a product whose name, description, and category contain this keyword.

**Comment by ephraimrosenfeld** [comment]
This functionality will be covered as a result of the changes in https://github.com/NYU-DevOps-Charlie-CSCI-GA-3033-013/products/issues/27. 

This issue can therefore be closed.
