### ISSUE TITLE
Research Product Catalog Data-sources

### ISSUE THREAD

**Issue by ephraimrosenfeld** [NYU-DevOps-Charlie-CSCI-GA-3033-013/products#4]
The scope of this is to find professional product catalog data-sources.

Some thoughts:
- Walmart and BestBuy APIs
- Ice-cat catalog mentioned in Slack channel

**Comment by rohithreddy1** [comment]
Below are the attributes for the Semantic API,

Product ID, Product name, Category_ID, Description, Brand name, Price, Price_Currency, Purchase URL, Availability, EAN, features, Model, Height, Weight, Width, UPC

Once we create an account, we would be assigned API Key and secret key. We can clone with the link
https://github.com/semantics3/semantics3-python.git.

Then we could set up using API key and secret key.

The data we receive from the API is regularly checked and refreshed bases on the ProductRank metric which Semantic uses to identify the important products.

Please let me know in case you need any further details.

Regards,
Rohith.

**Comment by ephraimrosenfeld** [comment]
This sounds perfect. It has additional attributes that we would want and (ostensibly) does not have any proprietary restrictions.

@rohithreddy1, were you able  to get a sample dump of the data?

**Comment by rohithreddy1** [comment]
@ephraimrosenfeld No, I will try to get sample data now. Will attach once done.
