### ISSUE TITLE
Extend API Calls

### ISSUE THREAD

**Issue by NicholasHyland** [NYU-DevOps-Charlie-CSCI-GA-3033-013/products#8]
Create more advanced RESTful API calls:

- Query resources by some attribute of the resource

**Comment by ephraimrosenfeld** [comment]
Closing this issue as it is addressed by individual issues:

- Adding a 'Discontinue' action: https://github.com/NYU-DevOps-Charlie-CSCI-GA-3033-013/products/issues/19
- Query by price: https://github.com/NYU-DevOps-Charlie-CSCI-GA-3033-013/products/issues/17
- Search key by description and name: https://github.com/NYU-DevOps-Charlie-CSCI-GA-3033-013/products/issues/18
